{"stderr":":memory::4:5: error: wrong number of arguments in call. Expected 2 arguments, got 3\n  0003 | func test() {\n> 0004 |     h(f(12), g(4), 12);\n             ^^^^^^^^^^^^^^^^^^\n  0005 | }\n:memory::4:7: error: can not use void where value of type bool is expected\n  0003 | func test() {\n> 0004 |     h(f(12), g(4), 12);\n               ^^^^^\n  0005 | }\n:memory::4:14: error: can not use void where value of type bool is expected\n  0003 | func test() {\n> 0004 |     h(f(12), g(4), 12);\n                      ^^^^\n  0005 | }\n"}